name: music_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  assets_audio_player: ^3.0.5
  audio_video_progress_bar: ^1.0.0
  audioplayers: ^3.0.1
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.7.4+1
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.4.2
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  firebase_auth: ^4.4.1
  firebase_core: ^2.6.1
  flutter:
    sdk: flutter
  flutter_downloader: ^1.8.4
  flutter_local_notifications: ^13.0.0
  flutter_native_splash: ^2.2.9
  flutter_svg: ^2.0.1
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.2.1
  internet_connection_checker: ^1.0.0+1
  page_transition: ^2.0.9
  path_provider: ^2.0.11
  permission_handler: ^10.0.2
  persistent_bottom_nav_bar: ^5.0.2
  shimmer: ^2.0.0
  url_launcher: ^6.1.5
  firebase_core_platform_interface: ^4.5.1
  firebase_messaging: ^14.2.4
  video_player: ^2.6.1

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/native_x.png
    - assets/images/Group_30.png
    - assets/images/
    - assets/icons/

  fonts:
    - family: AppFont
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf

flutter_native_splash:
  #  color: "#1C1E26"
  #  color: "#212332"
  color: "#121212"
  image: assets/images/native_x.png
  branding_mode: center
